services:
  - type: web
    name: nfl-hub-new-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    healthCheckPath: /api


